export enum Vertical {
  FOOD_AND_BEVERAGE = 'F&B',
  RETAIL = 'Retail',
  HEALTH_CARE = 'Health Care',
  BEAUTY = 'Beauty',
  HOME = 'Home',
  ELECTRONICS = 'Electronics',
  GAMING = 'Gaming',
  ENTERTAINMENT_LIFESTYLE = 'Entertainment/Lifestyle',
  FASHION = 'Fashion',
  AVIATION = 'Aviation',
  FMCG = 'FMCG',
  HOSPITALITY = 'Hospitality',
  TOURISM = 'Tourism',
  FINANCE = 'Finance',
  AUTOMOTIVE = 'Automotive',
  LUXURY = 'Luxury',
  TECH = 'Tech',
  EDUCATION = 'Education',
  REALESTATE = 'Realestate',
  TELECOME = 'Telecome',
  TOBACCO = 'Tobacco',
  FITNESS_AND_WELLNESS = 'Fitness and wellness',
  LOGISTICS_TRANSPORT = 'Logistics/transport',
  CRYPTO = 'Crypto',
}
