export enum Concept {
  MEME = 'Meme',
  GRWM = 'GRWM',
  ANIMATION_3D = '3D Animation',
  RECIPES = 'Recipes',
  STORY_TELLING_BY_IMAGES = 'Story telling by images',
  VIRAL_SONGS = 'Viral Songs',
  POV = 'POV',
  INFLUENCER_CONTENT = 'Influencer Content',
  CELEBRITY_CONTENT = 'Celebrity Content',
  INFORMATIVE = 'Informative',
  LIST = 'List',
  HAULS = 'Hauls',
  UNBOXING = 'Unboxing',
  HACKS = 'Hacks',
  CSR = 'CSR',
  LIVE_COVERAGE = 'Live Coverage',
  COUNTDOWNS = 'Countdowns',
  POLLS = 'Polls',
  UGC = 'UGC',
  COMPILATIONS = 'Compilations',
}
